### PR TITLE
Ssl certificate urllib3

### PR DESCRIPTION
**Pull request by fatzh**
Remove SSL warning during upload with urllib3 as explained here : https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

### CODE REVIEW

**Comment by tocker** [comment]
@fatzh can you please provide an example of the warning you're getting, including any details required to reproduce it?

**Comment by acomets01** [comment]
This is what I get using pycloudinary 1.8.0, when doing

`import cloudinary`
`from cloudinary import uploader`
`cloudinary.config(cloud_name='my_cloud_name', api_key='my_api_key', api_secret='my_api_secret')`
`response = uploader.upload(filepath, secure=True)`

> /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning:
> 
> Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

**Comment by taragano** [comment]
Hi @acomets01,
From our tests, we could reproduce the issue you referred to, however, the solution offered in the PR doesn't seem to change the warning, unfortunately. While we're still working on resolving it, please note that it's "only" a warning and not an error.

**Comment by acomets01** [comment]
I just tried on a locally cloned version of pycloudinary and did not get the warning...

**Comment by taragano** [comment]
Thank you for the update @acomets01, I'm glad it's working well for you now :)
Please let us know if there's anything else we can help you with.

**Comment by mybrainishuge** [comment]
@acomets01 
> I just tried on a locally cloned version of pycloudinary and did not get the warning... This seems to resolve the issue for me!

Do you no longer get the warning on a fresh clone of pycloudinary 1.8.0 or do you no longer get the warning on a clone of pycloudinary that includes the changes in fatzh's PR?

I'm still receiving this warning on 1.8.0 when invoking `uploader.upload`
```
/Users/richard/.virtualenvs/qa/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

**Comment by acomets01** [comment]
@mybrainishuge I am still using a clone of @fatzh s PR and it's working fine

**Comment by mybrainishuge** [comment]
@acomets01 Thanks for the quick reply and clarification!

@taragano Are there plans to merge this PR?

**Comment by tocker** [comment]
@fatzh and all - thanks for the pull request and comments!

**Comment by dbinetti** [comment]
So is this going to actually be released or should we point to master? @tocker @taragano

**Comment by taragano** [comment]
@dbinetti, @mybrainishuge - Version 1.9.0 was just published.
Please try it and let us know how it's working for you?

**Comment by mybrainishuge** [comment]
@taragano No more warnings with 1.9.0! Thanks!

**Comment by taragano** [comment]
Great! Thanks for the update @mybrainishuge :)

**Pull request merged**
