### PR TITLE
Django110 support

### PR DESCRIPTION
**Pull request by jarekwg**
Hiyas,
This is a start on a pull request for Django 1.10 support. It addresses the removal of the SubfieldBase class.
Bit busy to test it at the moment, but I think it should work..

Thought I'd throw it up here sooner rather than later, in case others want to help finish it off and merge. Else I'll come back to it in a few days/weeks. :)

### CODE REVIEW

**Comment by leonardocintra-luizalabs** [comment]
+1

**Comment by jarekwg** [comment]
Thanks for the bumps.

Linking issue #74 here as it's relevant.

Also, I didn't phrase my opening post particularly reassuringly, but I'm fairly confident now that there's nothing more add here and it's good to merge. The tests pass and it works fine in my django110 project.

**Comment by sebslomski** [comment]
@tocker Are there any objectives open before this can be merged?

**Comment by wli** [comment]
@tocker I believe this also addresses #67. Any chance this could be reviewed and merged? This is a compatibility blocker for Django 1.10, which is the latest version and has been out for 2 months now.

**Comment by jskopek** [comment]
+1. This is preventing us from upgrading to Django 1.10

**Comment by arbroen** [comment]
+1

**Comment by benjigoldberg** [comment]
+1 this is a blocker for us. Would love to see this merged and released.

**Comment by hillarysanders** [comment]
+1, blocker

**Comment by ETinLV** [comment]
+1, blocker.

**Comment by jdotjdot** [comment]
Can this please be merged? I've literally had to remove Cloudinary from my site because of this because it's blocking upgrade.

**Comment by jarekwg** [comment]
You can always fork this fix and pin your requirements to the commit while waiting for it to be merged.

**Comment by jdotjdot** [comment]
Yes, and I've done that with other libraries, but it's a pain--and this is a service that I pay for as opposed to just an open source library I'm using.

I only had to remove it from `INSTALLED_APPS` rather than entirely, that would have been a different story.

**Comment by wli** [comment]
Thanks for merging this @jdotjdot. Any word on when this will be released to PyPi?

**Comment by tocker** [comment]
Version 1.5.0 which includes this PR has been published to PyPi.

Thanks for the PR!

Please let us know if you have any issues with the new release!

**Pull request merged**
