### PR TITLE
Fixed CloudinaryField when blank=True

### PR DESCRIPTION
**Pull request by godshall**
Fix for #81

### CODE REVIEW

**Comment by tocker** [comment]
Hi @godshall ,

Thanks for submitting this pull request!

Unfortunately this solves the symptom but not the problem. The error occurs because python is testing for Truth using `len()` which is defined as [`len(self.public_id)`](https://github.com/cloudinary/pycloudinary/blob/55003b4bc281c0c65ff38a4e1be041df9ebd7fd6/cloudinary/__init__.py#L129). When public_id is None the error is raised.

Furthermore `value is None` seems to be standard for `from_db_value` (see [official doc](https://docs.djangoproject.com/en/1.10/howto/custom-model-fields/#converting-values-to-python-objects)).

I'm pushing soon a more comprehensive solution that would support None values in the CloudinaryField.

**Comment by godshall** [comment]
Hi @tocker,

Thanks for your feedback!

Regarding the doc you linked, you should only need to handle the `None` case if the field allows `null=True`.  I assumed that `CloudinaryField` does not allow `null=True` since its internal type is `CharField`, and it is recommended to avoid using null on Charfields (see [null docs](https://docs.djangoproject.com/en/1.10/ref/models/fields/#null)).  The previous versions of pycloudinary used the same approach.

If `CloudinaryField` really needs to handle the None case, then `parse_cloudinary_resource` will probably need to check `if not value` to handle the empty string properly.

**Comment by iMerica** [comment]
LGTM. This bug is a showstopper for me on Django 1.9 so the only way I'm able to use Pycloudinary is on my personal fork. 

Doing something as basic as this results in `Object of type 'NoneType' has no len()` error

```python
class Foo(models.Model):
  field = CloudinaryField('image', blank=True)

x = Foo.objects.create()
```

**Comment by richgieg** [comment]
Hi @godshall and @iMerica,

Version 1.6 of Pycloudinary was recently released, containing a fix for this issue. Is it working okay for you?

**Comment by godshall** [comment]
@richgieg I installed 1.6 last week and it seems to be working great.  Thanks for the follow-up!

**Pull request closed without merging**
